# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version 
Vagrant.configure(2) do |config|
# Every Vagrant development environment requires a box. You can search for
# boxes at https://atlas.hashicorp.com/search.
config.vm.box = "box-cutter/ubuntu1404-desktop"
config.vm.hostname = "Ref-Finder10"
config.vm.provider "virtualbox" do |vb|
# Display the VirtualBox GUI when booting the machine
vb.gui = true
# Customize the amount of memory on the VM:
vb.memory = "2048"
# Setting the virtual box name
vb.name = "Ref-Finder10"
end
config.vm.provision "shell", inline: <<-SHELL
# Java installation source : http://www.webupd8.org/2012/09/install-oracle-java-8-in-ubuntu-via-ppa.html
# The java installer requires you to accept the Oracle license before the installation begins. This is only required once. If for some reason you need the installation to be #automated, you can run the following command to automatically accept the Oracle license:
echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
sudo add-apt-repository ppa:webupd8team/java -y
sudo apt-get update
# The installer provides Oracle Java 8 (which includes Java JDK, JRE and the Java browser plugin)
sudo apt-get install oracle-java8-installer
# To automatically set up the Java 8 environment variables, you can install the following package:
sudo apt-get install -y oracle-java8-set-default

#Install eclipse Mars
sudo apt-get update
sudo wget --no-check-certificate https://github.com/aglover/ubuntu-equip/raw/master/equip_java8.sh && bash equip_java8.sh
echo "Starting eclipse download"
sudo wget -nv "http://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/mars/1/eclipse-rcp-mars-1-linux-gtk-x86_64.tar.gz&r=1" -O eclipse-rcp-mars-1-linux-gtk-x86_64.tar.gz
echo "Installing eclipse"
cd /home/vagrant && sudo tar xzf /home/vagrant/eclipse-rcp-mars-1-linux-gtk-x86_64.tar.gz
sudo ln -s /home/vagrant/eclipse/eclipse /home/vagrant/Desktop/eclipse


# Get Workspace
echo "***** Downloading Workspace with sample project *****"
sudo wget "https://github.com/SoftwareEngineeringToolDemos/FSE-2010-Ref-Finder/raw/master/build-vm/vm-contents/workspace.tar.gz" -O /home/vagrant/workspace.tar.gz
sudo tar -xvf /home/vagrant/workspace.tar.gz -C /home/vagrant/
sudo rm /home/vagrant/workspace.tar.gz
sudo chown -R vagrant "/home/vagrant/workspace"
sudo chmod -R a+rwx "/home/vagrant/workspace"

#Get Ref-Finder

wget -O "/home/vagrant/Desktop/LSclipse_1.0.4.tar" https://github.com/SoftwareEngineeringToolDemos/FSE-2010-Ref-Finder/raw/master/build-vm/vm-contents/LSclipse_1.0.4.tar.gz
sudo tar -xvf /home/vagrant/Desktop/LSclipse_1.0.4.tar -C /home/vagrant/Desktop/
sudo mv /home/vagrant/Desktop/LSclipse_1.0.4 /home/vagrant/eclipse/plugins
sudo chown -R vagrant "/home/vagrant/eclipse/plugins"
sudo chmod -R a+rwx "/home/vagrant/eclipse/plugins"


# Copy Installation file, License file, Readme, Youtube video link file and Acknowledgements file to desktop of the virtual machine
wget -O "/home/vagrant/Desktop/Readme.txt" https://github.com/SoftwareEngineeringToolDemos/FSE-2010-Ref-Finder/raw/master/build-vm/vm-contents/Readme.txt
wget -O "/home/vagrant/Desktop/Installation.txt" https://github.com/SoftwareEngineeringToolDemos/FSE-2010-Ref-Finder/raw/master/build-vm/vm-contents/Installation.txt
wget -O "/home/vagrant/Desktop/License.txt" https://github.com/SoftwareEngineeringToolDemos/FSE-2010-Ref-Finder/raw/master/build-vm/vm-contents/License.txt
wget -O "/home/vagrant/Desktop/Acknowledgement.txt" https://github.com/SoftwareEngineeringToolDemos/FSE-2010-Ref-Finder/raw/master/build-vm/vm-contents/Acknowledgement.txt
wget -O "/home/vagrant/Desktop/How to use on this tool.desktop" https://github.com/SoftwareEngineeringToolDemos/FSE-2010-Ref-Finder/raw/master/build-vm/vm-contents/Youtube%20Video.desktop
sudo chown -R vagrant "/home/vagrant/Desktop"
sudo chmod -R a+rwx "/home/vagrant/Desktop"

cd /home/vagrant/eclipse
sudo ./eclipse -clean -data /home/vagrant/workspace

SHELL
end
